### ISSUE TITLE
Error: Parse error @:4:24

### ISSUE THREAD

**Issue by ITLiuQing** [element-plus/unplugin-element-plus#171] opened 2022-11-18 15:10 UTC
**version："^0.4.1"**
configureWebpack: (config) => {
        config.plugins = [
            require('unplugin-element-plus/webpack')({
                // options
                useSource:true
            })
        ]
    },
npm run serve 
error:
Error: Parse error @:4:24
    at parse (/Users/mike/learn-pro/vue3-el-plus/node_modules/_es-module-lexer@0.10.5@es-module-lexer/dist/lexer.cjs:1:404)
    at transformStyle (/Users/mike/learn-pro/vue3-el-plus/node_modules/_unplugin-element-plus@0.4.1@unplugin-element-plus/dist/chunk-DAGBP3HE.js:46:43)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at runNextTicks (node:internal/process/task_queues:65:3)
    at processImmediate (node:internal/timers:437:9)
    at async Object.transform (/Users/mike/learn-pro/vue3-el-plus/node_modules/_unplugin@0.7.2@unplugin/dist/webpack/loaders/transform.js:75:15) {
  idx: 84
}

**Comment by sxzz** [comment] 2023-02-16 23:21
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

https://antfu.me/posts/why-reproductions-are-required

**Comment by sxzz** [comment] 2023-02-16 23:22
Try to upgrade your node version to latest LTS which is node 18

**Closed by sxzz** 2023-02-16 23:21 UTC
